### ISSUE TITLE
noHide param not work with polyline

### ISSUE THREAD

**Issue by stdex** [Leaflet/Leaflet.label#106]
Need to use param noHide: true with polyline. It's not work...
Example: http://jsfiddle.net/jypp24oq/5/

**Comment by stdex** [comment]
Wrapper that can do it:
http://jsfiddle.net/wangjin9112/8y4rfmje/6/

**Comment by jacobtoye** [comment]
`noHide` will not work on vectors as you say, see https://github.com/Leaflet/Leaflet.label/pull/97.
