### ISSUE TITLE
How to do labels above line vector

### ISSUE THREAD

**Issue by stdex** [Leaflet/Leaflet.label#107]
How to rotate labels? Need to show labels above lines vectors and will position labels parallel lines.

**Comment by stdex** [comment]
For example we do it:
http://jsfiddle.net/wangjin9112/8y4rfmje/7/
How can we fix the scale and location of the label so that it was always constant?

**Comment by seadour** [comment]
If you are using Leaflet.label or markers, you will have to write a function to change the size of the label or marker when the user changes the zoom level. Try this suggestion on Stackexchange: https://stackoverflow.com/questions/17382012/is-there-a-way-to-resize-marker-icons-depending-on-zoom-level-in-leaflet
