### ISSUE TITLE
Problem with circleMarker label's offset

### ISSUE THREAD

**Issue by jbouffand** [Leaflet/Leaflet.label#119]
Hello

First, thanks for this great plugin!

I have a problem with label's offset. I made a map with many circleMarkers, and each of it have a label, and the offset for each is [5,0]. It works only for the first circleMarker. With the following circleMarker, there is a growing gap between circleMarkers and labels, as you can see 
<a href="http://jbouffand.free.fr/cartes/routes_de_la_soie/new_1.html" target="_blank"> following this link.</a>

Can you help me?

**Comment by seadour** [comment]
Instead of setting the offset in your Javascript, try modifying the padding of the `.leaflet-label` class in your CSS. This will apply the same padding (offset) to all of your labels. You can also customize the font, background, etc. through the CSS.

**Comment by jbouffand** [comment]
Thanks for your answer. I realized that I forgot to create a link to the leaflet-labet.css file! I apologize for my stupidity!

**Comment by seadour** [comment]
Glad to hear it. Can you close this issue when you get a chance? Thank you.
