### ISSUE TITLE
Zoom level based class

### ISSUE THREAD

**Issue by a1an77** [Leaflet/Leaflet.label#124]
Is there a possibility to have a different class assigned to the labels depending on the map zoom level? It would be useful for having different font sizes or colour at different zoom levels.

the zoom level could be added alongside the specified class name, such as zoom-level-NN

**Comment by a1an77** [comment]
Is there no interest at all in such a feature? Any pointer at how to implement it eventually?

**Comment by IvanSanchez** [comment]
You can just

```js
map.on('zoomend', function(){
    if (  /* calculate if the zoom level change implies a label style change */ ) {
        /* change label style */
    }
});
```

**Comment by a1an77** [comment]
Thanks @IvanSanchez  that is indeed an option but it cuts off css, which would be cleaner (even though it might require defining up to 20 subclasses or so. I'll try your workaround meanwhile.

**Comment by IvanSanchez** [comment]
> that is indeed an option but it cuts off css, which would be cleaner 

```js
map.on('zoomstart', function(){
    L.DomUtil.removeClass(map.getContainer(), 'zoom-' + map.getZoom());
});
map.on('zoomend', function(){
    L.DomUtil.addClass(map.getContainer(), 'zoom-' + map.getZoom());
});
```

You were saying? :-)

(Just beware of fractional zoom level support in Leaflet 1)

**Comment by alexcroox** [comment]
Is there a function for changing `className`? Like there is `setContent` for example, but `setClassName` doesn't work

**Comment by alexcroox** [comment]
`marker.label.options.className = 'test';` does the trick

**Comment by a1an77** [comment]
Works like a charm @IvanSanchez thanks
