### ISSUE TITLE
The label is not always in the same position when zooming

### ISSUE THREAD

**Issue by ayasha88** [Leaflet/Leaflet.label#125]
I have a problem with the labels binded to some markers when zooming in and out. In the following pictures you can see an example of the problem:

![cattura](https://cloud.githubusercontent.com/assets/7511228/9466953/a4ed70a6-4b38-11e5-9e50-1e86ccfb417a.PNG)
![cattura2](https://cloud.githubusercontent.com/assets/7511228/9466961/a8330780-4b38-11e5-9dcb-e7c130d89b39.PNG)
![cattura3](https://cloud.githubusercontent.com/assets/7511228/9466964/abc5801c-4b38-11e5-92e8-2ce60ff3b706.PNG)
![cattura4](https://cloud.githubusercontent.com/assets/7511228/9466967/ae6c41de-4b38-11e5-9afe-b1ec7902db10.PNG)

As you can see when I zoom in the label is always closer to my marker. The problem is that I always want it to be as the last picture, that is simply under my marker.

Here is my code:

```js
  var myPos = new L.latLng(lat, lon); //lat and lon are coordinates defined above 
  var markerMyPos = L.marker(myPos, {
      icon: myIcon
  }); 
  markerMyPos.bindLabel('Some text', { noHide: true, className: 'marker_label', direction: 'right', offset: [-70, 0] }).addTo(map);
```

This happens mostly when I am at a low level of zoom and go down fast, instead if I am already at a high level of zoom and zoom more then the labels are nearer to the marker...

**Comment by seadour** [comment]
It might have something to do with your 'marker_label' class, or there might be something else in your Javascript code that is transforming the DOM / altering the label's anchor point on zoom events.

Can you replicate this example in a JSFiddle / Plunker for us?

Also, can you clarify what you mean by your last sentence? I'm not totally sure I follow you. Does the behavior change based on your starting zoom level?

**Comment by ayasha88** [comment]
Oh I think I resolved.. I forgot to add the leaflet.label.css file.. Thanks!

**Comment by seadour** [comment]
Glad to hear it. Can you close this issue for us? Thanks!
