### ISSUE TITLE
Updating label content

### ISSUE THREAD

**Issue by alexcroox** [Leaflet/Leaflet.label#127]
How do I update the label text after creation?

I've tried:

`marker.label._updateContent('test');`

`marker.updateLabelContent('test');`

`marker.label.updateLabelContent('test');`

**Comment by tmcw** [comment]
```js
marker.label.setContent('test');
```

?

**Comment by alexcroox** [comment]
Tried that as well

**Comment by alexcroox** [comment]
Ah my fault, was trying to use an int for the value, converting it to a string first fixed it.
