### ISSUE TITLE
Labels moving.

### ISSUE THREAD

**Issue by Brandantl** [Leaflet/Leaflet.label#133]
Sometimes when zooming in and out real quick the label will detach from the icon and fly somewhere else. It corrects itself when you zoom out/in again.

Anyone know how to fix this issue?

**Comment by seadour** [comment]
Are you using any other Leaflet plugins or Javascript libraries besides Leaflet.label? Which version of Leaflet are you using?

Can you reproduce this for us in a Codepen/Plunker/jsFiddle?

**Comment by Brandantl** [comment]
leaflet.js header does not include a versoin (sorry I don't know).

http://cad.oregon911.net/js/leaflet.js
http://cad.oregon911.net/js/Leaflet.label.js

It uses
jquery v1.7.2  and that's it.

Here's a jsFiddle of the problem, it occurs in the update simulation block. This is a very simplified version of the "update" system I used.. The bug still occurs on it.
http://jsfiddle.net/apewf0nm/14/

Zoom in and out and it'll occur faster. It will self correct on the next update (in this case 1 second), however the website does not update every 1 second so it could stay like that for 10-15 seconds or until the user zooms in and out a bunch of times.

**Comment by tmcw** [comment]
<img width="469" alt="2015-10-14 at 6 57 pm" src="https://cloud.githubusercontent.com/assets/32314/10500339/6d9aad82-72a5-11e5-9adf-c57124d566f7.png">

It's 0.7.3

**Comment by Brandantl** [comment]
Sorry I was looking at the comment header block which is cut out by Cloudflare. Thanks!

/*
 Leaflet, a JavaScript library for mobile-friendly interactive maps. http://leafletjs.com
 (c) 2010-2013, Vladimir Agafonkin
 (c) 2010-2011, CloudMade
*/

**Comment by seadour** [comment]
I think sometimes the zoom events are getting "caught" between cycles of the `loop()` function you wrote. Instead of running a loop, try binding your label recalculations to an event listener for the Leaflet zoom event.

    map.on('zoomend', function() {
      //label changes here
    });

In this way, it will only trigger the marker/label/whatever changes when the user actually changes the zoom level.

Documentation on the `zoomend` event is here: http://leafletjs.com/reference.html#map-zoomend

**Comment by Brandantl** [comment]
That won't work because then the user would have to zoom to refresh a dynamic 911 call map. If the title of the call changes so should the label on update, not when they change the zoom. http://www.cad.oregon911.net/

One possible solution would be to block zooming in/out on update but that seems like a hack.

**Comment by seadour** [comment]
Ah! I see. Tricky.

Maybe instead of blocking zoom during update, you could block update during `zoomstart` and wait until `zoomend` to update?

**Comment by Brandantl** [comment]
Thank you sedour, that appears to have fixed the demo!
http://jsfiddle.net/apewf0nm/22/

**Comment by seadour** [comment]
Yes!! Glad to hear it. Can you close this issue when you get a chance? Thanks.
