### ISSUE TITLE
L.bindTooltip throws error in console

### ISSUE THREAD

**Issue by explorer14** [Leaflet/Leaflet.label#167]
Hi,

I am trying to use bindTooltip() against a polygon that I am drawing on the map (using leaflet 1.0.2 and Mapbox.js API), but it throws an error in the console: "Cannot read property '_panes' of undefined". Debugging it using in browser dev tools, led to this line in leaflet.draw.js:

![image](https://cloud.githubusercontent.com/assets/1242932/25480999/2fc37338-2b43-11e7-9adc-b7bffac37592.png)

The param 't' of the initialise function (which I am assuming should be the map variable) is undefined, not sure why.  Here's my code that calls the bindTooltip() function:

```
_map.on('draw:created', function(eventInvoker){
     var _shapeLabel = "test";
     featureGroup.addLayer(eventInvoker.layer);
     eventInvoker.layer.bindTooltip(_shapeLabel);
     //..other code
});
```
Can someone help please? Not sure if this is a known bug or I am doing something wrong. I am trying to migrate from bindLabel() which used to work flawlessly with shapes.

Cheers
Aman

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by explorer14** [comment]
Here you go! this is the first time I have setup any of these code sharing tools, so formatting might be messy. Please let me know if this works:

https://playground-leaflet.rhcloud.com/pizu/edit?html,output

Cheers
Aman

**Comment by IvanSanchez** [comment]
Cannot reproduce with latest version of Leaflet and Leaflet.Draw. Your bug has been probably fixed some time during the past.

See https://playground-leaflet.rhcloud.com/vuji/edit?html,output

**Comment by explorer14** [comment]
I see! So may be this is happening for me because I am using Mapbox.js which in turn is probably using a slightly older version of leaflet.js. Thanks for taking time to help.

**Comment by IvanSanchez** [comment]
You're welcome 😄 . Just check your versions next time 😉
