### ISSUE TITLE
Static labels do not play with leaflet.markercluster

### ISSUE THREAD

**Issue by bertbesser** [Leaflet/Leaflet.label#35]
Hi,

first of all thanks for the plugin, in particular for static labels and the ability to have several labels display at the same time.

However, when using your plugin together with markercluster, static labels do not show up again when a marker is unclustered. Furthermore, once the zoom level changes, a static label of a marker, that was unclustered before and is still unclustered, disappears.

Best regards,
ugh-bough

**Comment by gommo** [comment]
I get this still too on iPad etc..

**Comment by Klapsa2503** [comment]
The issue also appears in JavaFX app. Labels are not rendered outside visible bounds.
