### ISSUE TITLE
Map markers are overlap tooltip

### ISSUE THREAD

**Issue by chekhA** [Leaflet/Leaflet.label#91]
If I add two pin to the map both have tootlip created with bindLabel method then one of the pins overlap tooltip.

For reproduce this issue on you demo (http://leaflet.github.io/Leaflet.label/) you can drag "A sweet static label" pin to the the "Look revealing label" pin and try open tooltip for this label. 

Actual result: tooltip are overlaped by pin.

**Comment by torfsen** [comment]
Using the `pane` option works great, here's the code in case anyone is having the same problem:

```
marker.bindLabel('My Label', {pane: 'popupPane'});
```
