### ISSUE TITLE
noHide doesn't work on paths

### ISSUE THREAD

**Issue by NOtherDev** [Leaflet/Leaflet.label#96]
There's no possibility to define static label on paths - it's implemented only for markers. Would be nice to have the same options for all elements.

**Comment by blake-regalia** [comment]
I agree with @NOtherDev, this should at least work for circles. It wouldn't be terribly difficult to allow an option for user to specify where the label should be placed with respect to the shape/path (ie: center of circle/edge of circle, the node index of a polyline, or the center of polygon/node index of polygon shape). At the very least, please clarify that this functionality is only available for icons in the readme.
