### ISSUE TITLE
get the content of the label?

### ISSUE THREAD

**Issue by willsand** [Leaflet/Leaflet.label#98]
Is there a way to get the content of the label?
feature.label.setContent() works to set it but how can i get the label?

feature.label.content returns undefined.

Thank you in advance and thanks for creating this plugin :-)

**Comment by p4535992** [comment]
Hi, sorry to re-open the discussion on this closed issue, but it's just give me nuts, i try to find a solution on the web but i failed, so sorry to bother you.
Classic use, i put some marker on map with Leaflet.Label, now i go to inspect every marker in the map, with the "eachLayer" and "onEachFeature" function of leaflet and i just want to get the text of the label, but i must doing something wrong, i put a piece of code for make myself more clear:
``` js

L.geoJson(someGeojsonFeature, {
     onEachFeature: function (feature, layer) {
         var textLabel = feature.label._content; //it's work 
      }
});

markerClusters.eachLayer(function (layer) {
          var textLabel1 = layer.getLabel()._content;  //is this the right way???
          var textLabel2 = layer.Label._content;   // or is this???
         //FIREFOX say: layer.getLabel(..) is undefined.
         //CHROME say: Cannot read property '_content' of undefined.
});

```
ty in advance for any help.

**Comment by willsand** [comment]
shouldn't "layer.Label._content" be "layer.label._content"?

**Comment by p4535992** [comment]
... and now I feel like an idiot, this is the correct solution thanks very much.

**Comment by willsand** [comment]
np i know the feeling ;-)
